export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const LOGOUT = 'LOGOUT';

export const ADD_GROUP = 'ADD_GROUP';
export const FETCH_GROUP_LIST = 'FETCH_GROUP_LIST';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';

export const ADD_MEMBER = 'ADD_MEMBER';
export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST';
export const SEARCH_MEMBER = 'SEARCH_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const RESET_MODAL_STATE = 'RESET_MODAL_STATE';

export const ADD_BILL = 'ADD_BILL';
export const FETCH_BILL_LIST = 'FETCH_BILL_LIST';
export const SEARCH_BILL = 'SEARCH_BILL';
export const DELETE_BILL = 'DELETE_BILL';
export const RESET_BILL_MODAL_STATE = 'RESET_BILL_MODAL_STATE';

export const FETCH_GROUP_EXPENSES_SUMMARY = 'FETCH_GROUP_EXPENSES_SUMMARY';
export const FETCH_GROUP_EXPENSES_DETAILS = 'FETCH_GROUP_EXPENSES_DETAILS';